name: Perform Checks
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions: write-all
jobs:
  run:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Pylint action
        uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
          glob_pattern: "**/*.py"
      - name: Add Badges
        # You may pin to the exact commit or the version.
        # uses: wow-actions/add-badges@43f2c1eaecfb2596b89a8136a3fbda4f18d1d188
        uses: wow-actions/add-badges@v1.1.0
        env:
          repo_url: ${{ github.event.repository.html_url }}
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.event.repository.owner.login }}
        with:
          # Your GitHub token for authentication.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The badges to add with JSON format
          badges: |
            [
              {
                "badge": "https://img.shields.io/badge/License-MIT-yellow.svg?style=for-the-badge",
                "alt": "MIT License",
                "link": "${{ env.repo_url }}/blob/main/LICENSE"
              },
              {
                "badge": "https://img.shields.io/badge/Language-Python-blue?style=for-the-badge&logo=python",
                "alt": "Language",
                "link": "https://www.python.org/"
              },
              {
                "badge": "https://img.shields.io/badge/PRs-Welcome-brightgreen.svg?style=for-the-badge",
                "alt": "PRs Welcome",
                "link": "${{ env.repo_url }}/pulls"
              }
            ]
          # Path and file name to add badges
          path: README.md
          # Should center align the badges
          center: false
      - name: Release Version
        id: version
        run: echo "VERSION=$(python3 setup.py --version)" >> "$GITHUB_ENV"
      - name: Show version
        run: echo $VERSION
      - uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"