name: Release New Version
on:
  push:
    branches:
      - main
jobs:
  prepare:
    permissions: write-all
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/action-demo/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/
      # retrieve your distributions here
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: "https://test.pypi.org/legacy/"
      - name: Release Version
        id: version
        run: echo "VERSION=$(python3 setup.py --version)" >> $GITHUB_ENV
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease
          use_github_release_notes: true
          release_name: "Release ${{ env.VERSION }}"
